#!/usr/bin/env node

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

var path=require('path');
var util=require('util');
var net=require('net');
var framing=require('utils-for-aprs').framing;
var APRSProcessor=require('utils-for-aprs').APRSProcessor;
var EventEmitter=require('events');
var log4js=require('log4js');
var logger=log4js.getLogger('main');

log4js.configure('log-config.json');
logger.debug("logging system setup.");

console.log("process.argv=" + process.argv);

//Open the tcp port
var serverSocket=net.createServer();

// On open, install a handler that prints the data.
serverSocket.on('connection', function(conn) {
  console.log("Port opened");
  var parseFrame=framing.tncFrameParser();
  var aprsProcessor=new APRSProcessor();
  var emitter=new EventEmitter();
  conn.on('data', function(data) {
  console.log('Got data');
    try {
      if (data) {
        parseFrame(emitter, data);
      } else {
        console.log('...data was null');
      }

    } catch(err) {
      console.log("Bad frame:", err);
      console.log(data);
    }
  });
  emitter.on('data', function(data) { aprsProcessor.data(data); });
  aprsProcessor.on('aprsData', function(data) {
    console.log('got aprsData');
    console.log(data);
  });
  var logger=log4js.getLogger('aprs');
  aprsProcessor.on('error', function(err, frame) {
    logger.error("Got error on received frame." + err);
    logger.debug(frame);
  });

});

serverSocket.listen(3001, function() {
  console.log("TCP Server socket opened on port 3001");
})
